#!/usr/bin/env python3
# FreeRDP: A Remote Desktop Protocol Implementation
#
# Generate CMake package files for find_package() parity, replacing what CMake's
# configure_package_config_file() + write_basic_package_version_file() +
# install(EXPORT) produce (Meson has no native generator for these).
#
# Emits into <out_dir>:
#   <Name>Config.cmake         - from the upstream <Name>Config.cmake.in template
#                                (@PACKAGE_INIT@ + @VAR@ substitution)
#   <Name>ConfigVersion.cmake  - SameMajorVersion compatibility check
#   <Name>Targets.cmake        - the imported target(s)
#
# Usage:
#   gen_cmake_package.py <out_dir> <template|-> <name> <version> <cmake_install_dir>
#       <targets_spec> [VAR=value ...]
#
#   <cmake_install_dir>  install path of the Config files relative to prefix
#                        (e.g. lib64/cmake/FreeRDP3) -- used to compute PACKAGE_PREFIX_DIR
#   <targets_spec>       ';'-separated imported targets, each:
#                        name,libfile,incdir[,link1|link2|...]
#                        (libfile/incdir are relative to the install prefix)
import os
import sys


PACKAGE_INIT_TMPL = """
####### Expanded from @PACKAGE_INIT@ by gen_cmake_package.py #######
get_filename_component(PACKAGE_PREFIX_DIR "${{CMAKE_CURRENT_LIST_DIR}}/{up}" ABSOLUTE)

macro(set_and_check _var _file)
  set(${{_var}} "${{_file}}")
  if(NOT EXISTS "${{_file}}")
    message(FATAL_ERROR "File or directory ${{_file}} referenced by variable ${{_var}} does not exist !")
  endif()
endmacro()

macro(check_required_components _NAME)
  foreach(comp ${{${{_NAME}}_FIND_COMPONENTS}})
    if(NOT ${{${{_NAME}}_${{comp}}_FOUND}})
      if(${{${{_NAME}}_FIND_REQUIRED_${{comp}}}})
        set(${{_NAME}}_FOUND FALSE)
      endif()
    endif()
  endforeach()
endmacro()
####################################################################
"""

VERSION_TMPL = """\
# Generated by gen_cmake_package.py (write_basic_package_version_file equivalent)
set(PACKAGE_VERSION "{version}")

if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)
  set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()
  if("{major}" STREQUAL "${{PACKAGE_FIND_VERSION_MAJOR}}")
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
  else()
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
  endif()
  if(PACKAGE_FIND_VERSION STREQUAL PACKAGE_VERSION)
    set(PACKAGE_VERSION_EXACT TRUE)
  endif()
endif()
"""


def main():
    out_dir, template, name, version, cmake_install_dir, targets_spec = sys.argv[1:7]
    var_args = sys.argv[7:]

    os.makedirs(out_dir, exist_ok=True)
    major = version.split('.')[0]

    # PACKAGE_PREFIX_DIR: climb out of <prefix>/<cmake_install_dir> back to <prefix>.
    depth = len([p for p in cmake_install_dir.replace('\\', '/').split('/') if p])
    up = '/'.join(['..'] * depth)
    package_init = PACKAGE_INIT_TMPL.format(up=up)

    variables = {'PACKAGE_INIT': package_init}
    for a in var_args:
        key, _, value = a.partition('=')
        variables[key] = value

    # The upstream rdtk/uwac templates include("rdtk.cmake")/("uwac.cmake") rather
    # than "<Name>Targets.cmake"; let the caller override the targets filename.
    targets_file = variables.pop('TARGETS_FILENAME', name + 'Targets.cmake')

    # --- <Name>Config.cmake (from upstream template) ---
    if template != '-':
        with open(template, 'r', encoding='utf-8') as handle:
            content = handle.read()
        for key, value in variables.items():
            content = content.replace('@{}@'.format(key), value)
    else:
        content = '@PACKAGE_INIT@\ninclude("${{CMAKE_CURRENT_LIST_DIR}}/{f}")\n'.format(f=targets_file)
        content = content.replace('@PACKAGE_INIT@', package_init)
    with open(os.path.join(out_dir, name + 'Config.cmake'), 'w', encoding='utf-8') as handle:
        handle.write(content)

    # --- <Name>ConfigVersion.cmake ---
    with open(os.path.join(out_dir, name + 'ConfigVersion.cmake'), 'w', encoding='utf-8') as handle:
        handle.write(VERSION_TMPL.format(version=version, major=major))

    # --- <Name>Targets.cmake (imported targets) ---
    lines = ['# Generated imported targets for {} (install(EXPORT) equivalent)'.format(name)]
    for spec in targets_spec.split(';'):
        if not spec:
            continue
        parts = spec.split(',')
        tgt, libfile, incdir = parts[0], parts[1], parts[2]
        links = parts[3] if len(parts) > 3 else ''
        lines += [
            'if(NOT TARGET {t})'.format(t=tgt),
            '  add_library({t} SHARED IMPORTED)'.format(t=tgt),
            '  set_target_properties({t} PROPERTIES'.format(t=tgt),
            '    IMPORTED_LOCATION "${{PACKAGE_PREFIX_DIR}}/{f}"'.format(f=libfile),
            '    INTERFACE_INCLUDE_DIRECTORIES "${{PACKAGE_PREFIX_DIR}}/{d}"'.format(d=incdir),
        ]
        if links:
            lines.append('    INTERFACE_LINK_LIBRARIES "{l}"'.format(l=links.replace('|', ';')))
        lines += ['  )', 'endif()']
    with open(os.path.join(out_dir, targets_file), 'w', encoding='utf-8') as handle:
        handle.write('\n'.join(lines) + '\n')


if __name__ == '__main__':
    main()
